import type { Metadata } from "next";

import { Providers } from "#/app/providers";
import { sansStatic, sansVariable } from "#/utils/font";

import "../index.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={`${sansVariable.variable} ${sansStatic.variable}`}
			dir="rtl"
			lang="fa-IR"
		>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
